name: Build Appimage
on:
  workflow_dispatch:

concurrency:
  group: builder
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "accept-flake-config = true"

      - name: Build Appimage via nix bundle
        run: nix bundle --bundler github:ralismark/nix-appimage github:chaotic-cx/nyx/nyxpkgs-unstable#firedragon

      - name: Get version right
        run: filename=$(ls | grep firedragon)

      - name: Upload Appimage
        uses: actions/upload-artifact@v3
        with:
          name: FireDragon AppImage
          path: *.AppImage